### ISSUE TITLE
Make filtered top sites reset upon re-installation

### ISSUE THREAD

**Issue by aidanhorton** [aidanhorton/ecosia-darkmode-extensions#10]
You can press the 'X' to filter a site from the Chrome new tab page, see below:
![image](https://user-images.githubusercontent.com/22588585/112824540-8f582980-9082-11eb-98a8-586f8745d435.png)

Currently there's no way to reset this if you remove a site.
So either add a method to manage filtered sites, or reset this upon re-installation of the extension potentially?

Would be interesting to hear if this is something users would value.

**Comment by OppnedKatt** [comment]
In this feature, would the ability to only remove certain ones be necessary or wanted? Got a version of it were it just resets them all working.

**Comment by aidanhorton** [comment]
As long as you can still remove individual ones from showing, I don't see a problem with resetting them all!

**Comment by OppnedKatt** [comment]
Should the top sites update right away after resetting, or should you have to reload the new tab in order to see an effect?

**Comment by aidanhorton** [comment]
> Should the top sites update right away after resetting, or should you have to reload the new tab in order to see an effect?

Not sure I see a massive problem with having to reload. In the ideal world it would update instantly, but I wouldn't really mind either way - I expect because of how the newtab page works, it would be pretty tough to make it update immediately - so maybe we just keep it simple and ask for a refresh!

**Comment by OppnedKatt** [comment]
I'll look into it on Friday. I have an idea of how I could do it, but not time atm.
