### ISSUE TITLE
Banners on certain pages seem to have changed their class or something on that line

### ISSUE THREAD

**Issue by OppnedKatt** [aidanhorton/ecosia-darkmode-extensions#17]
![bilde](https://user-images.githubusercontent.com/68151654/137590954-b58920b5-e814-453f-9948-b7f048e04dfc.png)
As the image above shows the banner on search is not dark. I managed to click on it on accident, so I can't really test it anymore. In the code it is correct for home-page, but not search
![bilde](https://user-images.githubusercontent.com/68151654/137591302-041f93ce-1257-423f-aa04-23da9faab981.png)
![bilde](https://user-images.githubusercontent.com/68151654/137591340-deea7b69-d91b-432c-a2f2-2c5b661122ab.png)
I can try to see if I can understand the fork thing, and send in something

**Comment by OppnedKatt** [comment]
Sorry for have taken so long, but I've been quite busy with school, and will continue to be busy for a while forward. Unless you don't mind me taking some time before I'm able to begin, you would probably want to do it yourself. I looked a little bit into it earlier before closing the banner on mistake, I think I concluded with that you would only need to add .banner classes under the /*Notifications banner */ that would change the file.

**Comment by aidanhorton** [comment]
I'm in no rush as it's not an issue that affects me 😁

I'll leave it on hold for a few weeks, so if you still fancy giving it a go, then feel free! Otherwise I might check it out in a month or so.

No rush at all 😉

**Comment by OppnedKatt** [comment]
I think created to Pull Request or whatever it is called (still don't really have any experience with Github) for the search-page and the settings-page. 

I have no idea on what is up about the thing on the bottom of the one for the settings-page as I didn't even touch that part. 
![bilde](https://user-images.githubusercontent.com/68151654/144726524-845c7756-4701-4b6a-bb91-670c2cbccb3b.png)

**Comment by aidanhorton** [comment]
@OppnedKatt Awesome stuff!

Unfortunately there are no opened Pull Requests on this repository - follow this guide to get one setup, since you have a fork of my repository :)

https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork

**Comment by OppnedKatt** [comment]
I have now given it another attempt
