### ISSUE TITLE
Put the extension on the Microsoft Edge Addons store

### ISSUE THREAD

**Issue by MaXfAa** [aidanhorton/ecosia-darkmode-extensions#19]
I suggest to post the extension on the Microsoft Edge Addons store:
https://aka.ms/publishedgeaddons

**Comment by aidanhorton** [comment]
Thanks for the suggestion!
I did try to upload it a while ago but I was getting some server errors meaning I literally couldn't upload the package! :(

Will try again ASAP and see if it works now 😄

**Comment by MaXfAa** [comment]
> Thanks for the suggestion! I did try to upload it a while ago but I was getting some server errors meaning I literally couldn't upload the package! :(
> 
> Will try again ASAP and see if it works now 😄

Ok perfect, thanks !! 😉

**Comment by aidanhorton** [comment]
@MaXfAa just an update:

I've submitted a support request to Microsoft as I've been trying for hours at this point to upgrade my Manifest to V3 from V2. Aswell as that I've followed Chrome -> Edge migration and the portal just isn't accepting the extension. Awaiting reply from MS :)

**Comment by MaXfAa** [comment]
> @MaXfAa just an update:
> 
> I've submitted a support request to Microsoft as I've been trying for hours at this point to upgrade my Manifest to V3 from V2. Aswell as that I've followed Chrome -> Edge migration and the portal just isn't accepting the extension. Awaiting reply from MS :)

Ok, keep me informed 😉

**Comment by aidanhorton** [comment]
I'll give another shot at this sometime again soon. MS never got back to me on my issue - I'll try contacting them again.

I need to update this extension to Manifest V3 for Chrome, so I'll use that to troubleshoot any issues and then hopefully it should be drag+drop into Edge. We'll see!

**Comment by aidanhorton** [comment]
Managed to finally get Manifest v3 working after using Chrome to debug.
Currently uploading to the store and should hopefully be available within 7 days @MaXfAa 😄 

![image](https://user-images.githubusercontent.com/22588585/171445902-ad02e5be-dcbc-47b6-ada7-020e4480fbdc.png)
