### ISSUE TITLE
Issue: Fix Wikipedia logo on search

### ISSUE THREAD

**Issue by thundercrypt** [aidanhorton/ecosia-darkmode-extensions#2]
![Screenshot 2021-01-31 133853](https://user-images.githubusercontent.com/77282722/106378329-c800bd00-63c9-11eb-8370-d3d117b49b75.png)
The Wikipedia Logo appears dark on a dark background, please fix

Excellent work BTW 😊
Actually, I don't know javascript so can't submit a pull request

**Comment by aidanhorton** [comment]
I've changed it to now be more of a white colour:
![image](https://user-images.githubusercontent.com/22588585/106384374-786ac300-63c2-11eb-93be-a2333417b686.png)

This will be uploaded and approved by Google hopefully later today

The way the theme works is to basically inject CSS into the webpage - so this change was pretty much just a small CSS change.

As for JS, I really don't know it myself either, so the code may be a bit of a mess to any outsiders 😂

And thanks! :)

**Comment by aidanhorton** [comment]
Closed by commit: https://github.com/aidanhorton/ecosia-darkmode-extensions/commit/0aa8c9546605a2a9ed72568e141ca1de1dc8070a

**Comment by thundercrypt** [comment]
> I've changed it to now be more of a white colour:
> ![image](https://user-images.githubusercontent.com/22588585/106384374-786ac300-63c2-11eb-93be-a2333417b686.png)
> 
> This will be uploaded and approved by Google hopefully later today
> 
> The way the theme works is to basically inject CSS into the webpage - so this change was pretty much just a small CSS change.
> 
> As for JS, I really don't know it myself either, so the code may be a bit of a mess to any outsiders 😂
> 
> And thanks! :)

Not a problem. Loved your work, that Ecosia light mode was really a strain on the eyes 😉
