### ISSUE TITLE
White highlight on typing in searchbox

### ISSUE THREAD

**Issue by OppnedKatt** [aidanhorton/ecosia-darkmode-extensions#20]
After having searched and you go onto changing the contents of the searchbox while having your mouse hovered over a result and then typing, the background-color will look somewhat like HTML's Azure colour. If you move your mouse so it doesn't hover over the same element anymore it goes back to how it should behave. 

![bilde](https://user-images.githubusercontent.com/68151654/151040999-7aafc177-73f3-4170-ab53-d9b7bc25d2e1.png)
![bilde](https://user-images.githubusercontent.com/68151654/151041036-673e9c31-d580-4dec-bb5b-c24298c3b535.png)

**Comment by aidanhorton** [comment]
Thanks for reporting this! Seems like a weird one, but likely I'm just missing a style somewhere for one of the states!

I'll look into it when I get the chance :)

**Comment by OppnedKatt** [comment]
After making a little script, I found the cause of the issue:
![bilde](https://user-images.githubusercontent.com/68151654/153757263-695e34e5-6db8-4db6-9f67-db09affe3a4d.png)

Might see if I can fix it and commit it to my current open pull request.

**Comment by OppnedKatt** [comment]
Have committed the changes to the pull request.

**Comment by aidanhorton** [comment]
Apologies - will check the PR out soon, have been snowed under with work!

**Comment by OppnedKatt** [comment]
No worries. I have stuff to work on myself.

**Comment by OppnedKatt** [comment]
Fixed in PR #23.
