### ISSUE TITLE
Box around floating ads

### ISSUE THREAD

**Issue by Rexogamer** [aidanhorton/ecosia-darkmode-extensions#21]
Hey! Thanks for the extensions - this has certainly helped my eyes!

I've noticed that, for searches with "floating" ads, there seems to be a weird box around the ads?

![image](https://user-images.githubusercontent.com/42586271/152652195-25329337-89ac-408a-bf6e-791bfb29ca26.png)

This doesn't show on the default theme:

![image](https://user-images.githubusercontent.com/42586271/152652207-205f1f96-ada8-450b-9b7c-bc3e56355350.png)

**Comment by aidanhorton** [comment]
Thanks! 😊

Interesting issue - thanks for reporting it! Should hopefully be a simple fix - I'll add it to the list of work for the next update!

**Comment by aidanhorton** [comment]
@Rexogamer this issue should now be fixed! Thanks for reporting!
Let me know if you have any other issues :)
