### ISSUE TITLE
Some error of reading property of null in the newtab.js file

### ISSUE THREAD

**Issue by OppnedKatt** [aidanhorton/ecosia-darkmode-extensions#22]
I found this error while working on the time based Darkmode:
![bilde](https://user-images.githubusercontent.com/68151654/153721031-28ecac7a-59fc-43e5-adcb-33ac3f6781a0.png)

Doing something with wraping it in an if that checks if mostVisited !== null, and maybe more if needed would work, but I haven't looked too much into the newtab page, so I will just leave it here.

**Comment by OppnedKatt** [comment]
I don't know if this has any effect on the newtab page

**Comment by OppnedKatt** [comment]
I checked the newtab page for a different reason and noticed that there were no mostVisited there. Maybe just a bug on my end, or maybe it is not supposed to work yet?

**Comment by aidanhorton** [comment]
Is this still an issue on the PR you created? Or have you not seen this issue since you reported it? Just wondering whether this can be closed or not :)

**Comment by OppnedKatt** [comment]
I fixed it. Should I add it to a new PR, or #25? As #25 is one that I feel like may just be put on the shelf for having the blinking problem it has.

**Comment by aidanhorton** [comment]
Sounds like a new PR is the way to go - thanks for helping out!
