### ISSUE TITLE
There is no styling for Ecosia's Store page

### ISSUE THREAD

**Issue by OppnedKatt** [aidanhorton/ecosia-darkmode-extensions#24]
The title explains it self.

**Comment by OppnedKatt** [comment]
This may be the result of links being changed or something.

**Comment by OppnedKatt** [comment]
Changed the title as I added a fix for the FAQ in my currently open pull request. I gave fixing the store an attempt, but that was a nightmare, so I'll just not touch that. Here is the new link to the store page: https://plant.ecosia.org/*. I did not include the change in the PR as the JS currently breaks the site entirely.

**Comment by OppnedKatt** [comment]
There are some other sites missing styling too.

**Comment by aidanhorton** [comment]
Thanks! Being realistic, not sure if I'll ever get to that - I guess it depends on if this ever becomes tightly integrated with the search engine or not!

But I'll keep it open as an issue either way!

**Comment by OppnedKatt** [comment]
To be honest, I don't really care about it myself, and I looked itno it a bit, and noticed that they have just made the top of some of the images rounded, as in the white part being inside the image it selv. You vould maybe cut it off with border-radius-top-left and so or something, but the shop site just seems like a nightmare to make work.

**Comment by aidanhorton** [comment]
Since it's not part of the search engine itself, decided to close this for now. If anyone ever really wants this in future we can re-open - but reality is that it likely won't be worked on, so I'll close this to avoid bloating the issues.
