### ISSUE TITLE
Time-activation issue - uninstallations peaked

### ISSUE THREAD

**Issue by aidanhorton** [aidanhorton/ecosia-darkmode-extensions#26]
So there must be a bug of some sort with the new time-activated dark mode - as the day I uploaded the change, the uninstallations peaked higher than they've ever been:
![image](https://user-images.githubusercontent.com/22588585/158597249-494c5217-f97a-490a-87e0-1cd27aed7f4f.png)

I have no idea what the issue could be. I didn't get a chance to test this - but does it default to enabled if the setting doesn't exist in local storage? By default it's off, correct?
It could be that the update required new permissions - namely permissions for ecosia.zendesk.com - I noticed that it asked me if I wanted to allow the extension new information in my FireFox browser - so it could just be that. We just need to make sure this feature is functional. So I will likely try an installation on a brand new browser installation and see what happens.

Just want to make sure we haven't broken anything!

**Comment by OppnedKatt** [comment]
By default it is set to off.

**Comment by OppnedKatt** [comment]
There should be absolutely no way that it can default to on. If they had previously turned off the extension, it would ignore the old setting, and start fresh with the new format of storing it. I could have made it convert old settings, but that would be done every time you open the popup, and not just the first time, so it would lead to a lot of unnecessary evaluations I feel. So they may have uninstalled it if they weren't using it anyway, and it just turned it self back on.

**Comment by OppnedKatt** [comment]
But making the conversion thing would maybe be a bit too late now as there has been some time, and most people have probably already updated it and so.

**Comment by OppnedKatt** [comment]
I'm sorry that I forgot to mention this about it :/

**Comment by OppnedKatt** [comment]
Some people may have also stopped using Ecosia, so they may have felt like giving it the new permissions, or just still having it installed would be unnecessary.

**Comment by aidanhorton** [comment]
> If they had previously turned off the dark-mode option it would ignore the old setting, and start fresh with the new format of storing it. I could have made it convert old settings, but that would be done every time you open the popup, and not just the first time, so it would lead to a lot of unnecessary evaluations and data-gathering I feel. So they may have uninstalled it if they weren't using it anyway, and it just turned it self back on.

That's completely fine, if people can't live with that, then they probably shouldn't have the extension installed 😄 
Yeah I think it may just be the new permissions thing for people who have stopped using Ecosia - in future we'll take notes and be careful with new permissions - but it's good to know we probably didn't do anything wrong!

Since I use FireFox, I have no idea how Chrome asks for new permissions, do you have any idea how it does that? Just wondering if Chrome offers the option to uninstall right next to the 'Give Permissions' (or equivalent), button - which just makes it super easy to uninstall

**Comment by OppnedKatt** [comment]
I don't have the extention on Chrome as I don't use Chrome. So no, I have no idea. Used chrome a while back, but I can't remember much. 

But the details on the extentionpage may be a bit outdated when it come to the premissions (thinking about ecosia.zendesk.com).

**Comment by OppnedKatt** [comment]
But was this on Firefox and/or Chrome?

**Comment by aidanhorton** [comment]
This was Chrome only. Looked like uninstalls on FireFox were relatively stable if I remember correctly. I think we can close this now as the uninstalls have gone back to normal - so I assume it would just be an update of permissions thing - just something to consider in future:
![image](https://user-images.githubusercontent.com/22588585/159249132-c18ab2e4-4ca1-4f07-90ab-23b8a14815d5.png)
