### ISSUE TITLE
Styling tweaks v1.3.0.0

### ISSUE THREAD

**Issue by aidanhorton** [aidanhorton/ecosia-darkmode-extensions#27]
Ecosia's latest round of changes have caused a few small issues:
![image](https://user-images.githubusercontent.com/22588585/158988086-274d9bf2-103d-4e0b-8d7e-229f028c2661.png)
![image](https://user-images.githubusercontent.com/22588585/158988106-e5dd5d17-e86f-419a-ac38-a447e6787e24.png)

The new URL format means that URLs are no longer green on light-mode, so we may need to consider a new colour scheme in order to fit better:
![image](https://user-images.githubusercontent.com/22588585/158988187-6f9eb5f9-c225-4487-8077-2285ec48cb67.png)
![image](https://user-images.githubusercontent.com/22588585/158988199-d738a977-64f8-4a7b-9426-a0a84f5bddb7.png)

**Comment by OppnedKatt** [comment]
As for the colour scheme, adding how it is right now as a separate theme from a new one that could match Ecosia's new changes could be a thing. After the changes from #25 there would only need to be made a few changes for different themes to be a thing. Though there would need to be made quite a few more changes to make the things from the different themes carry over to the light-mode.

**Comment by aidanhorton** [comment]
Could potentially go for different themes - simpler solution for now is to just make it a bit more like it is in light mode (I'll trust Ecosia's designers to have a better colour scheme), and in future maybe we can add full tweaking support, or ability to switch between themes.

**Comment by OppnedKatt** [comment]
Is this change still there for you on normal Ecosia? I at least still have green URLs

**Comment by aidanhorton** [comment]
Should be fixed by https://github.com/aidanhorton/ecosia-darkmode-extensions/pull/29 !
