### ISSUE TITLE
MAJOR ISSUE: Ecosia Homepage showing incorrect inversion

### ISSUE THREAD

**Issue by thundercrypt** [aidanhorton/ecosia-darkmode-extensions#3]
Attaching a screenshot for further details. Or, you can simply visit the website yourself.

![image](https://user-images.githubusercontent.com/77282722/106379326-2d0be100-63d1-11eb-847c-fb80c2a279cd.png)

**Comment by aidanhorton** [comment]
Thanks! Looks like Exodia recently updated the page, I'll get this fixed ASAP.

Estimate: 1-2 days

**Comment by thundercrypt** [comment]
> Thanks! Looks like Exodia recently updated the page, I'll get this fixed ASAP.
> 
> Estimate: 0-2 days

No Problem. It's what devs are for, right? :D

**Comment by aidanhorton** [comment]
Close by commit: https://github.com/aidanhorton/ecosia-darkmode-extensions/commit/0aa8c9546605a2a9ed72568e141ca1de1dc8070a
