### ISSUE TITLE
Update to manifest v3

### ISSUE THREAD

**Issue by aidanhorton** [aidanhorton/ecosia-darkmode-extensions#30]
Update the extension to use manifest.json v3 - as this is the new standard that will eventually be enforced.
This will give us speedier reviews, and new APIs. On top of that, the process for getting this extension into the Edge store should be much easier - as that enforces manifest v3, but just doesn't have good error messages when trying to upload it to the store.
![image](https://user-images.githubusercontent.com/22588585/159249402-961c221f-c6bd-433d-b96b-5aa38f8d4104.png)

**Comment by OppnedKatt** [comment]
Have you made a draft of it or something like that yet?

**Comment by aidanhorton** [comment]
> Have you made a draft of it or something like that yet?

Not sure how I keep missing all of these notifications!
I do have a draft for this, I'll upload it to a branch relatively soon. Manifest v2 is being phased out of Chrome completely by 2023 so there is an eventual deadline for this too!

**Comment by OppnedKatt** [comment]
Github is bad at giving me notifications too. The push-notifs just started working for me again, but for the last while I've had to rely on getting mails.

**Comment by aidanhorton** [comment]
This has now been completed as part of this commit!
https://github.com/aidanhorton/ecosia-darkmode-extensions/commit/6cd471e84da00b56e939b431dab431d8082ac5cd
