### ISSUE TITLE
Unify result card styles

### ISSUE THREAD

**Issue by aidanhorton** [aidanhorton/ecosia-darkmode-extensions#31]
Small issue, but to my eye it's a touch inconsistent. But some cards have borders, some cards have shadows. Some cards have lighter backgrounds, some cards have the same background as the search page. It would be nice to unify these styles as the light-mode has consistent styling on these.

Examples:
![image](https://user-images.githubusercontent.com/22588585/159252735-466f7288-8cc5-4bd7-a964-5da253e9618d.png)
![image](https://user-images.githubusercontent.com/22588585/159252780-f79f2228-0a81-4272-a3d2-9e197b6789d0.png)

**Comment by OppnedKatt** [comment]
Ecosia them selves seem to use shading around the cards.

**Comment by aidanhorton** [comment]
Yeah I used to have shadows around side-bar cards - but that must've just gotten lost in the updates that I've done to the styles over time. Think I'll switch to a white shadow if it doesn't look too bad!

**Comment by OppnedKatt** [comment]
With #38 this seems to have been resolved. 
![bilde](https://user-images.githubusercontent.com/68151654/172923798-e0d880ca-f0d0-4dbc-8197-a22a6fedba1c.png)

**Comment by aidanhorton** [comment]
> With #38 this seems to have been resolved.

Excellent stuff! Thanks for confirming - I'll close this issue in that case :)
