### ISSUE TITLE
Video-cards styling issue

### ISSUE THREAD

**Issue by OppnedKatt** [aidanhorton/ecosia-darkmode-extensions#37]
![bilde](https://user-images.githubusercontent.com/68151654/171422346-ef269b3d-466f-48d8-a236-922e9bd33964.png)
Seems like the padding is being overwritten. I don't have time to look at this myself. Have a lot of stuff to do atm.

**Comment by OppnedKatt** [comment]
![bilde](https://user-images.githubusercontent.com/68151654/171427034-4feabd27-4dd8-4401-bf66-a629d6f9391e.png)
Seems like Ecosia has removed the background-colour for it

**Comment by aidanhorton** [comment]
Thanks for the report! Hoping this will get fixed as part of https://github.com/aidanhorton/ecosia-darkmode-extensions/issues/34, as I potentially have quite a slick solution to reduce the CSS by almost 90%, whilst also being much more stable. It should solve issues such as this!
But I wont get too ahead of myself, this may not work. But either way I'll fix it in the next batch! :)
