### ISSUE TITLE
The extension got kinda brokey recently 

### ISSUE THREAD

**Issue by stansters** [aidanhorton/ecosia-darkmode-extensions#39]
I think their "new look" broke some parts of the extension

![image](https://user-images.githubusercontent.com/91402728/172858239-b234128d-7b43-455c-bd5f-73dad45a2dc5.png)

**Comment by OppnedKatt** [comment]
Some of it have gotten fixes ready already. I have found out what we need to do to fix most things here, but the border around the shopping-tab is new to me as I can't see the shopping-tab

**Comment by stansters** [comment]
> Some of it have gotten fixes ready already. I have found out what we need to do to fix most things here, but the border around the shopping-tab is new to me as I can't see the shopping-tab

alright, thanks :D

**Comment by aidanhorton** [comment]
> I think their "new look" broke some parts of the extension
> 
> ![image](https://user-images.githubusercontent.com/91402728/172858239-b234128d-7b43-455c-bd5f-73dad45a2dc5.png)

Thanks for reporting the issues!
Just for extra clarity, I released v1.4.0.0 of the extension a few hours ago - it's successfully passed validation for FireFox, but not Chrome yet. It should be verified by tomorrow, and that patch should fix the vast majority of styling issues in their new update! Hang tight and there will be more changes soon to fix the rest :)
