### ISSUE TITLE
Redundant Firefox permission

### ISSUE THREAD

**Issue by OppnedKatt** [aidanhorton/ecosia-darkmode-extensions#45]
Some people choose some other Ecosia Darkmode extension on Firefox as the result of that one having fewer necessary permissions. I did notice that on Firefox, the extension still says on the add-ons-site that it requires the browsing history, even though that is only applicable for Chrome as that's the only place where the extension has a new tab page, and that the manifest only says tabs and storage. I don't know how the things are on the "extension-stores", so I don't know what you can do about that.

**Comment by aidanhorton** [comment]
> Some people choose some other Ecosia Darkmode extension on Firefox as the result of that one having fewer necessary permissions. I did notice that on Firefox, the extension still says on the add-ons-site that it requires the browsing history, even though that is only applicable for Chrome as that's the only place where the extension has a new tab page, and that the manifest only says tabs and storage. I don't know how the things are on the "extension-stores", so I don't know what you can do about that.

I think I fixed this in a recent change - but that's weird, I thought I uploaded that change to the web store... I'll check this out but I'm fairly sure the 'TopSites' permission is no longer in the manifest!

**Comment by aidanhorton** [comment]
@OppnedKatt just uploaded the latest version - I must've missed uploading a version to FireFox at some point, as this permission has now gone! Happy days :)

![image](https://user-images.githubusercontent.com/22588585/179548362-31c51795-2f57-4ab1-9b35-c09df1fae14d.png)
