### ISSUE TITLE
White flash upon page load Chrome

### ISSUE THREAD

**Issue by aidanhorton** [aidanhorton/ecosia-darkmode-extensions#47]
In Chrome I'm getting a white flash upon page load, or typing a new search term, or anything really that triggers the code to be re-run!
It's just a small white flash, but it's annoying and slightly concerning!

The number of active users on the extension has gone down by a fair bit recently too, so maybe the two are correlated? I think this would likely be something around the fixes done earlier to make the page defualt to dark mode.

I don't believe this is an issue in Firefox.

**Comment by OppnedKatt** [comment]
I am at least unable to get the white flashing, so there's not much I can do here.

**Comment by aidanhorton** [comment]
This may actually be fixed by this PR so I'll mark this as confirming resolution - I believe I saw this yesterday as I was on master, and on a very slow PC. Will try test this again once the new JS changes are in!

**Comment by OppnedKatt** [comment]
I was doing some testing on some stuff on my slower laptop, and this seems to be occurring to me now. Maybe this should be reopened? I'll do some more testing, and then it's up to you if you want to open this again.
