### ISSUE TITLE
Make crosses on newtab hidden until mouseover

### ISSUE THREAD

**Issue by thundercrypt** [aidanhorton/ecosia-darkmode-extensions#5]
Hi Aidan,

Is the new tab page supposed to have these crosses on it?

![image](https://user-images.githubusercontent.com/77282722/106414561-e4a4ff80-6472-11eb-95ef-cf9ed4e903d0.png)

**Comment by thundercrypt** [comment]
> ![image](https://user-images.githubusercontent.com/77282722/106414561-e4a4ff80-6472-11eb-95ef-cf9ed4e903d0.png)

Please ignore that notification :)

**Comment by aidanhorton** [comment]
Have you tried clicking one? 😉 

They are there because someone in the reviews section complained that you couldn't remove them - so I added the cross buttons so you could remove them. Ecosia does a very similar thing.

Granted, I could probably make them invisible until you mouseover - I may do that.

**Comment by thundercrypt** [comment]
Ohhh
Sorry, I didn't notice. I'll try figuring out potential solutions, even if it means digging up some JS 😃

**Comment by aidanhorton** [comment]
Just a full warning that it is one of the worst areas of code 😆

**Comment by thundercrypt** [comment]
I've yet to see that
But don't worry I'm probably like the worst at JS
I know Python, markdown, HTML, css, Visual Basic, small basic but not an ounce of JS

**Comment by aidanhorton** [comment]
I don't blame you, I don't like JS syntax at all - which is why I've put off learning it in any official capacity!

**Comment by thundercrypt** [comment]
It might take me a few days to go through all the code, my exams are coming up... I'll update on this thread a little later if that's fine, after reviewing the code

**Comment by thundercrypt** [comment]
Also, I have an idea if you don't wanna use JS...
I looked through the code and saw that you have the cross turn white whenever you hover over it. So can't we just find a cross with the same colo(u)r as the background? It'll then turn into a cross whenever someone hovers over it.

**Comment by aidanhorton** [comment]
Yep you could do! The only thing to consider with that, is that the user wouldn't know the cross existed - the only way they'd find that it existed as a feature is if they accidentally hovered over where the cross was.

Ecosia gets around this by making the cross visible if you hover over the main circular link for the webpage, then the cross appears on the left-hand-side.

**Comment by thundercrypt** [comment]
Okay...
So could we do the same thing?

**Comment by aidanhorton** [comment]
Yep should be possible! Will just require some a few JS changes as well as CSS & HTML changes to get that all sorted 👍

**Comment by thundercrypt** [comment]
Perfect

**Comment by OppnedKatt** [comment]
Have made a fix for it. Not exactly the same as Ecosia has done it as you can hover over where the X should be to make it show up, but I think it's just as fine. Will include it in a PR with some other things on the new tab as well.
