### ISSUE TITLE
Counter pop-out is white

### ISSUE THREAD

**Issue by Gersonzao** [aidanhorton/ecosia-darkmode-extensions#51]
The Tree counter pop-out is white

**Comment by aidanhorton** [comment]
@Gersonzao thanks for reporting this! Apologies for the delay too. I'll try and get this fully fixed within the next week along with a few other things. Thanks for using the extension!

**Comment by aidanhorton** [comment]
@Gersonzao apologies for the wait - this fix has now been uploaded to all extension stores. You should see the change applied in the next 24 hours :)

**Comment by Chirunos** [comment]
It's dark now!
