### ISSUE TITLE
Dark mode does not work on new chat-bot feature

### ISSUE THREAD

**Issue by stansters** [aidanhorton/ecosia-darkmode-extensions#54]
![image](https://github.com/aidanhorton/ecosia-darkmode-extensions/assets/91402728/013e0676-607a-4b28-9803-a7f53c9c214c)

**Comment by aidanhorton** [comment]
@stansters thanks for leaving an issue! It seems that the chat feature is a beta thats being slowly rolled out - this is generally how Ecosia rolls out large updates, so this means I dont actually have this feature yet to test it out!

However, that being said, I don't know if you're aware or not, but Ecosia as of relatively recently, now comes with a built-in darkmode - so hopefully that works on the chat page!

Let me know if this helps :)

![image](https://github.com/aidanhorton/ecosia-darkmode-extensions/assets/22588585/bf64ea7e-7415-468d-8793-0f68589020fc)
