### ISSUE TITLE
Feature Request: Style Ecosia Like Google

### ISSUE THREAD

**Issue by thundercrypt** [aidanhorton/ecosia-darkmode-extensions#8]
Hi,

Will it be possible to style Ecosia like Google?
I found a file on the net, hope it helps.
Just remember to allow ads as that's how Ecosia makes money 😄 :D

Here's the code: (has to upload in .txt format as it's not allowing .js files)
[ecosia-google-style-2019-no-ads-theme.user.txt](https://github.com/aidanhorton/ecosia-darkmode-extensions/files/5963211/ecosia-google-style-2019-no-ads-theme.user.txt)

**Comment by aidanhorton** [comment]
Well interestingly I was the one who created that file you just sent 😋
Back a year or so ago I did create a Google style, it didn't receive much attention so I stopped developing it.

It could be added as an option in this extension - but it would mean maintaining these 2 separate themes.

I'll look into it though 👍

**Comment by thundercrypt** [comment]
Oh, that's brilliant!
Means that you'd understand the working of it.

Okay, thanks!
This was a nice coincidence 😋

**Comment by aidanhorton** [comment]
Will close this issue for now as this is not high priority - nor do we know if people would even want this as a feature, lets keep it simple for now. We can always re-raise this 😄

**Comment by OppnedKatt** [comment]
We could add support for multiple styles without having to maintain two different styles for the most part, but there are two pages that still doesn't use the universal-styling. But with you saying something about redoing the CSS or something, I'll just wait on the sideline

**Comment by aidanhorton** [comment]
> We could add support for multiple styles without having to do too much and maintain two different styles for the most part, but there are two pages that still doesn't use the universal-styling. But with you saying something about redoing the CSS or something, I'll just wait on the sideline

Sure thing! I'll do the CSS update as soon as I can, and once we've done that, then maybe we can look at this! But just be aware that we don't want to make it tooooo heavy, as currently it's not exactly the most lightweight 😄 
But if you have an idea that you think would work without too much complexity, I'm happy to see and/or review anything! Happy to re-open this whenever.
